name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: Kajanthann   # <-- your GitHub username
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update snake"
          add: "dist/github-contribution-grid-snake.svg"
